version: '3.9'
services:

  db:
    build:
      dockerfile: ./home/work
    environment:
      TZ: "Europe/Moscow"
      MYSQL_ROOT_PASSWORD: 1234
    restart: unless-stopped
    volumes:
      - db: /var/lib/mysql
    networks:
      - app-network
    deploy:
      mode: replicated
      replicas: 2

  adminer:
    depends_on:
      - db
      image: nginx
      restart: always
      ports:
        - 8080:80
      volumes:
        - ./data/mysql:/var/lib/mysql
      networks:
        - app-network
      deploy:
        mode: replicated
        replicas: 1
  volumes:
    db:

  networks:
    app-network:
      driver: bridge
